version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: cineverse-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: cineverse

volumes:
  mongodb_data:
